name: mimic_google
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - keras
  - scikit-learn
  - spacy
  - pip
  - seaborn
  - jupyterlab
  - holoviews
  - hvplot
  - cython
  - pip:
    - google-cloud-storage
    - google-auth
    - ibis-framework[bigquery]
    - medspacy
    - itables
